import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:cli_util/cli_util.dart' as cli_util;
import 'package:interactive/src/utils.dart';
import 'package:interactive/src/vm_service_wrapper.dart';
import 'package:interactive/src/workspace_file_tree.dart';
import 'package:vm_service/vm_service.dart' as vm_service;

class WorkspaceIsolate {
  final VmServiceWrapper vm;
  final Process process;
  final String isolateId;
  bool _disposed = false;

  WorkspaceIsolate._({
    required this.vm,
    required this.process,
    required this.isolateId,
  }) {
    unawaited(
      process.exitCode.then((code) {
        if (!_disposed) {
          exit(code);
        }
      }),
    );
  }

  static Future<WorkspaceIsolate> create(
    WorkspaceFileTree workspaceFileTree,
  ) async {
    // Run pub get so that the package_config.json is generated and packages
    // are resolved correctly in the interpreter
    await _runPubGet(workingDirectory: workspaceFileTree.directory);

    final packageConfigFile = File(workspaceFileTree.pathPackageConfig);
    assert(
      packageConfigFile.existsSync(),
      'package_config.json does not exist at ${packageConfigFile.parent.path}',
    );

    final (process, serverUri) = await _spawnDartVmServiceProcess(
      scriptPath: workspaceFileTree.pathAutoGeneratedDart,
      packageConfigPath: packageConfigFile.path,
      workingDirectory: workspaceFileTree.directory,
    );

    final vm = await VmServiceWrapper.connect(serverUri);
    final isolateId = await _waitForMainIsolateId(vm.vmService);

    return WorkspaceIsolate._(vm: vm, process: process, isolateId: isolateId);
  }

  Future<vm_service.Isolate> get isolateInfo =>
      vm.vmService.getIsolate(isolateId);

  void dispose() {
    _disposed = true;
    vm.dispose();
    process.kill();
  }
}

String get _dartExecutable =>
    cli_util.dartExecutable ?? (Platform.isWindows ? 'dart.exe' : 'dart');

Future<(Process, Uri)> _spawnDartVmServiceProcess({
  required String scriptPath,
  required String packageConfigPath,
  required String workingDirectory,
}) async {
  final process = await Process.start(_dartExecutable, [
    '--enable-vm-service=0',
    '--disable-service-auth-codes',
    '--no-dds',
    '--no-serve-devtools',
    '--packages=$packageConfigPath',
    scriptPath,
  ], workingDirectory: workingDirectory);

  final serviceUriCompleter = Completer<Uri>();
  final bannerRegex = RegExp(
    r'The Dart VM service is listening on (http://\S+)',
  );

  process.stdout.transform(utf8.decoder).transform(const LineSplitter()).listen(
    (line) {
      if (!serviceUriCompleter.isCompleted) {
        final match = bannerRegex.firstMatch(line);
        if (match != null) {
          serviceUriCompleter.complete(Uri.parse(match.group(1)!));
          return;
        }
      }
      stdout.writeln(line);
    },
  );

  process.stderr.listen(stderr.add);

  unawaited(
    process.exitCode.then((code) {
      if (!serviceUriCompleter.isCompleted) {
        serviceUriCompleter.completeError(
          StateError(
            'Child Dart VM process exited with code $code before starting VM service.',
          ),
        );
      }
    }),
  );

  final serverUri = await serviceUriCompleter.future;
  return (process, serverUri);
}

Future<String> _waitForMainIsolateId(vm_service.VmService vmService) async {
  while (true) {
    final isolates = (await vmService.getVM()).isolates ?? const [];
    if (isolates.isNotEmpty) {
      final id = isolates.first.id;
      if (id != null) {
        final isolate = await vmService.getIsolate(id);
        if (isolate.rootLib != null) {
          return id;
        }
      }
    }
    await Future<void>.delayed(const Duration(milliseconds: 10));
  }
}

Future<void> _runPubGet({required String workingDirectory}) async {
  final cmd = getCrossPlatformCommand('$_dartExecutable pub get');

  final process = await Process.start(
    cmd.executable,
    cmd.arguments,
    workingDirectory: workingDirectory,
    runInShell: true,
  );

  final code = await process.exitCode;

  if (code != 0) {
    throw Exception(
      "pub get at '$workingDirectory' failed with exit code $code",
    );
  }
}
